use iwip;
SELECT CONCAT(json_object(
  "TENANT_ID", h.MANUFACTURER,
  "MANUFACTURER", h.MANUFACTURER,
  "PO_HEADER_ID", h.PO_HEADER_ID,
  "PURCHASE_ORDER_NUMBER", h.PURCHASE_ORDER_NUMBER,
  "REVISION_NUM", h.REVISION_NUM,
  "REVISED_DATE", h.REVISED_DATE,
  "PO_DATE", h.PO_DATE,
  "PO_STATUS", h.PO_STATUS,
  "TYPE_LOOKUP_CODE", h.TYPE_LOOKUP_CODE,
  "CREATION_DATE", h.CREATION_DATE,
  "LAST_UPDATE_DATE", h.LAST_UPDATE_DATE,
  "LAST_UPDATED_BY", h.LAST_UPDATED_BY,
  "SUMMARY_FLAG", h.SUMMARY_FLAG,
  "ENABLED_FLAG", h.ENABLED_FLAG,
  "FREIGHT_TERMS_LOOKUP_CODE", h.FREIGHT_TERMS_LOOKUP_CODE,
  "AUTHORIZATION_STATUS", h.AUTHORIZATION_STATUS,
  "APPROVED_FLAG", h.APPROVED_FLAG,
  "APPROVED_DATE", h.APPROVED_DATE,
  "CANCEL_FLAG", h.CANCEL_FLAG,
  "CLOSED_CODE", h.CLOSED_CODE,
  "VENDOR_NAME", h.VENDOR_NAME,
  "PARTY_ID", h.PARTY_ID,
  "PARTY_NUMBER", h.PARTY_NUMBER,
  "VENDOR_NUMBER", h.VENDOR_NUMBER,
  "PARTY_NUMBER", h.PARTY_NUMBER,
  'PO_STATUS', h.PO_STATUS,
'CREATION_DATE', json_object("$date", DATE_FORMAT(h.CREATION_DATE,'%Y-%m-%dT%TZ')), 
'PO_LINES', JSON_ARRAY(json_object(
								"MANUFACTURER", l.MANUFACTURER,
                                "PO_HEADER_ID", l.PO_HEADER_ID,
                                "PO_LINE_ID", l.PO_LINE_ID,
                                "LINE_NUM", l.LINE_NUM,
                                "ITEM_DESCRIPTION", REPLACE(l.ITEM_DESCRIPTION, "\"", "'"),
                                "UNIT_MEAS_LOOKUP_CODE", l.UNIT_MEAS_LOOKUP_CODE,
                                "NOTE_TO_VENDOR", l.NOTE_TO_VENDOR,
                                "SKU", l.SKU,
                                "QUANTITY_REMAINING", l.QUANTITY_REMAINING,
                                "EX_FACTORY_DATE", l.EX_FACTORY_DATE,
                                "PO_LINE_TYPE", l.PO_LINE_TYPE,
                                "QUANTITY_ORDERED", l.QUANTITY_ORDERED,
                                "QUANTITY_DELIVERED", l.QUANTITY_DELIVERED,
                                "QUANTITY_CANCELLED", l.QUANTITY_CANCELLED,
                                "SHIP_TO_LOCATION", l.SHIP_TO_LOCATION,
                                "SHIP_TO_SITE_DESCRIPTION", l.SHIP_TO_SITE_DESCRIPTION,
                                "SHIP_TO_LOCATION_ID", l.SHIP_TO_LOCATION_ID,
                                "ADDRESS_STYLE", l.ADDRESS_STYLE,
                                "ADDRESS_LINE_1", l.ADDRESS_LINE_1,
                                "ADDRESS_LINE_2", l.ADDRESS_LINE_2,
                                "ADDRESS_LINE_3", l.ADDRESS_LINE_3,
                                "TOWN_OR_CITY", l.TOWN_OR_CITY,
                                "COUNTRY", l.COUNTRY,
                                "POSTAL_CODE", l.POSTAL_CODE,
                                "REGION_1", l.REGION_1,
                                "REGION_2", l.REGION_2,
                                "TELEPHONE_NUMBER_1", l.TELEPHONE_NUMBER_1,
                                "ATTRIBUTE1", l.ATTRIBUTE1,
                                "ATTRIBUTE2", l.ATTRIBUTE2,
                                "ATTRIBUTE3", l.ATTRIBUTE3,
                                "DERIVED_LOCALE", l.DERIVED_LOCALE,
                                "TIMEZONE_CODE", l.TIMEZONE_CODE,
                                "NEED_BY_DATE", DATE_FORMAT(l.NEED_BY_DATE,'%Y-%m-%dT%TZ'),
                                "PROMISED_DATE", DATE_FORMAT(l.PROMISED_DATE,'%Y-%m-%dT%TZ'),
                                "LINE_CLOSED_CODE", l.LINE_CLOSED_CODE,
                                "LINE_LOCATION_ID", l.LINE_LOCATION_ID,
                                "ITEM_ID", l.ITEM_ID,
                                "NON_Z_ITEM_ID", l.NON_Z_ITEM_ID,
                                "BUILD_WEEK", l.BUILD_WEEK,
                                "SHIP_TO_SITE_REGION", l.SHIP_TO_SITE_REGION,
                                "LAST_UPDATE_DATE", DATE_FORMAT(l.LAST_UPDATE_DATE,'%Y-%m-%dT%TZ'),
                                "LAST_UPDATED_BY", l.LAST_UPDATED_BY,
                                "PO_ORDER_TYPE", l.PO_ORDER_TYPE
								)
)), ',') as 'json' 
INTO OUTFILE 'c:/wamp64/tmp/iw_po.json' ## IMPORTANT you may want to adjust outfile path here
FROM s_po_header h
INNER JOIN s_po_lines l ON l.PO_HEADER_ID = h.PO_HEADER_ID
WHERE YEAR(h.CREATION_DATE) IN (2001, 2022)
;