-- use iwip;
SELECT Concat(json_object("TENANT_ID", l.MANUFACTURER,
					"MANUFACTURER", l.MANUFACTURER,
					"PO_HEADER_ID", l.PO_HEADER_ID,
                    "PO_LINE_ID",   l.PO_HEADER_ID,
					"SHIP_TO_LOCATION", l.SHIP_TO_LOCATION,
					"SHIP_TO_SITE_DESCRIPTION", l.SHIP_TO_SITE_DESCRIPTION,
					"SHIP_TO_LOCATION_ID", l.SHIP_TO_LOCATION_ID,
					"ADDRESS_STYLE", l.ADDRESS_STYLE,
					"ADDRESS_LINE_1", l.ADDRESS_LINE_1,
					"ADDRESS_LINE_2", l.ADDRESS_LINE_2,
					"ADDRESS_LINE_3", l.ADDRESS_LINE_3,
					"TOWN_OR_CITY", l.TOWN_OR_CITY,
					"COUNTRY", l.COUNTRY,
					"POSTAL_CODE", l.POSTAL_CODE,
					"REGION_1", l.REGION_1,
					"REGION_2", l.REGION_2,
					"TELEPHONE_NUMBER_1", l.TELEPHONE_NUMBER_1,
					"ATTRIBUTE1", l.ATTRIBUTE1,
					"ATTRIBUTE2", l.ATTRIBUTE2,
					"ATTRIBUTE3", l.ATTRIBUTE3,
					"DERIVED_LOCALE", l.DERIVED_LOCALE,
					"TIMEZONE_CODE", l.TIMEZONE_CODE,
					"NEED_BY_DATE", DATE_FORMAT(l.NEED_BY_DATE,'%Y-%m-%dT%TZ'),
					"PROMISED_DATE", DATE_FORMAT(l.PROMISED_DATE,'%Y-%m-%dT%TZ'),
					"LINE_CLOSED_CODE", l.LINE_CLOSED_CODE,
					"LINE_LOCATION_ID", l.LINE_LOCATION_ID,
					"ITEM_ID", l.ITEM_ID,
					"NON_Z_ITEM_ID", l.NON_Z_ITEM_ID,
					"BUILD_WEEK", DATE_FORMAT(l.BUILD_WEEK,'%Y-%m-%dT%TZ'),
					"SHIP_TO_SITE_REGION", l.SHIP_TO_SITE_REGION,
                    "SHIPPING_DOCUMENTS", JSON_ARRAY(json_object(
											 "FILE_NAME", l.SHIP_TO_SITE_DESCRIPTION,
											 "MIME_TYPE", l.SHIP_TO_LOCATION_ID,
											 "CONTENT", l.ADDRESS_STYLE,
											 "CREATED_BY", l.ADDRESS_LINE_1,
											 "CREATE_DATE", l.ADDRESS_LINE_2
										  )
)), ',') as 'json' 
INTO OUTFILE 'c:/wamp64/tmp/iw_shipping.json'
FROM s_po_lines l
-- WHERE YEAR(l.CREATION_DATE) IN (2022)
;